id: vizbench_apptainer
description: An OMNI reconstruction of Jessica Li Group's single-cell 2D viz benchmark 
version: 0.01
benchmarker: "Mark D. Robinson, other contributors to be added"
benchmark_yaml_spec: 0.04
#storage: http://omnibenchmark.org:9000
#storage_api: S3
#storage_bucket_name: foo
software_backend: apptainer
software_environments:
  r-451-bioc-321-apptainer:
    description: "rocker/tidyverse:4.5.1-based image w/ Bioc 3.21 (NOTE: BioC/R packages not locked down)"
    apptainer: envs/r-451-bioc-321-apptainer.sif
    conda: envs/r-451-bioc-321-dummy.yml

stages:
  ## rawdata ##########################################################
  - id: rawdata
    modules:
      - id: mouse_pancreas 
        name: "mouse pancrease dataset from https://pubmed.ncbi.nlm.nih.gov/27667365/"
        software_environment: r-451-bioc-321-apptainer
        repository:
            url: https://github.com/markrobinsonuzh/vizbench-r
            commit: f33f957
        parameters:  
          - values: ["--what", "rawdata", "--flavour", "mouse_pancreas"] 
            #- values: ["--what", "rawdata", "--flavour", "xxx"]  # add other datasets
    outputs:
      - id: rawdata.ad
        path: "{dataset}_rawdata.ad"

  ## simulate ##########################################################
  - id: simulate
    modules:
      - id: scdesign3
        name: "simulator from scdesign3: https://doi.org/10.1038/s41587-023-01772-1"
        software_environment: r-451-bioc-321-apptainer
        repository:
            url: https://github.com/markrobinsonuzh/vizbench-r
            commit: f33f957
        parameters:
          - values: ["--what", "simulate", "--flavour", "scdesign3"]
    inputs:
      - entries:
          - rawdata.ad
    outputs:
      - id: simulate.ad
        path: "{dataset}_simulate.ad"

  ## normalize ##########################################################
  - id: normalize
    modules:
      - id: normalize-r
        name: "normalization functions implemented in R"
        software_environment: r-451-bioc-321-apptainer
        repository:
          url: https://github.com/markrobinsonuzh/vizbench-r
          commit: 6c681a8
        parameters:
            - values: ["--what", "normalize", "--flavour", "log1pCPM"]
            - values: ["--what", "normalize", "--flavour", "log1pCP10k"]
    inputs:
      - entries:
        - simulate.ad
    outputs:
      - id: normalize.ad
        path: "{dataset}_normalize.ad"
      - id: normalize.json
        path: "{dataset}_normalize.json"

  ## integrate ##########################################################
  - id: integrate
    modules:
      - id: integrate-r
        name: "integration methods implemented in R"
        software_environment: r-451-bioc-321-apptainer
        repository:
            url: https://github.com/markrobinsonuzh/vizbench-r
            commit: 7064153
        parameters:
          - values: ["--what", "integrate", "--flavour", "harmony"] # add other integration methods
          #- values: ["--what", "integrate", "--flavour", "fastMNN"] # add other integration methods
          #- values: ["--what", "integrate", "--flavour", "xx"] # add other integration methods
    inputs:
      - entries:
          - normalize.ad
          - normalize.json
    outputs:
      - id: integrate.ad
        path: "{dataset}_integrate.ad"


#    inputs:
#      - entries:
#          - data.matrix
#          - data.true_labels
#    outputs:
#      - id: clustering.predicted_ks_range
#        path: "{input}/{stage}/{module}/{params}/{dataset}_ks_range.labels.gz"

#  - id: metrics
#    modules:
#      - id: partition_metrics
#        name: "clustbench partition metrics"
#        software_environment: "clustbench"
#        repository:
#          url: https://github.com/imallona/clustbench_metrics
#          commit: 9132d45
#        parameters:
#          - values: ["--metric", "adjusted_mi_score"]
#          - values: ["--metric", "adjusted_rand_score"]
#    inputs:
#      - entries:
#          - clustering.predicted_ks_range
#          - data.true_labels
#    outputs:
#      - id: metrics.scores
#        path: "{input}/{stage}/{module}/{params}/{dataset}.scores.gz"

#metric_collectors:
#  - id: plotting
#    name: "Single-backend metric collector."
#    software_environment: "rmarkdown"
#    repository:
#      url: https://github.com/imallona/clustering_report
#      commit: 1d6bdf5
#    inputs:
#      - metrics.scores
#    outputs:
#      - id: plotting.html
#        path: "{input}/{name}/plotting_report.html"
